In [3]:
from thinc.api import HashEmbed, Maxout, Softmax, expand_window, Relu
from thinc.api import residual, strings2arrays, with_array, clone, chain, concatenate
from thinc.layers import noop

import ml_datasets

In [19]:
(train_X, train_y), (test_X, test_y) = data = ml_datasets.ud_ancora_pos_tags()
print(train_X[0])
print(f"\nSentente size: {len(train_X[0])}")

print(len(train_y[0]))
print(train_y[0])


# Transform a sequence of string sequences to a list of arrays.
s2a = strings2arrays()
emb, _ = s2a.begin_update(train_X[:1])

print(f"Output type: {type(emb)}")
print(f"Output size: {len(emb)}")
print(f"Output embedding type: {type(emb[0])}")
print(f"Output embedding shape: {emb[0].shape}")
print("The result:")
emb[0].T

['El', 'presidente', 'de', 'el', 'órgano', 'regulador', 'de', 'las', 'Telecomunicaciones', 'se', 'mostró', 'partidario', 'de', 'completar', 'esta', 'liberalización', 'de', 'las', 'telecomunicaciones', 'con', 'otras', 'medidas', 'que', 'incentiven', 'la', 'competencia', 'como', 'puede', 'ser', 'abrir', 'el', 'acceso', 'a', 'la', 'información', 'de', 'los', 'clientes', 'de', 'Telefónica', 'a', 'otros', 'operadores', '.']

Sentente size: 44
44
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0

array([[18446744072083554475, 18446744073255727043,            543259558,
        18446744072252264504,           1103121568,           1399176523,
                   543259558,            797000761,           1617915982,
        18446744072931898881,           1195312295,             87281376,
                   543259558, 18446744071926469705,            723188833,
        18446744072928539352,            543259558,            797000761,
        18446744073045935379,            807352699,           1025333401,
        18446744073667574632,            785491873, 18446744073006937574,
                   823349694, 18446744072810868504,           1245366323,
                   278659925, 18446744072541521126, 18446744073147948567,
        18446744072252264504, 18446744071590211959,           1009084850,
                   823349694,           1774907633,            543259558,
                  1789020513, 18446744073434962215,            543259558,
        18446744072843995569,         

In [6]:
# Transform sequence data into a contiguous two-dimensional array on the way into and out of a model.

with_a = with_array(noop())
a, _ = with_a.begin_update(emb)

In [10]:
print(f"Output type: {type(a)}")
print(f"Output size: {len(a)}")
print(f"Output embedding type: {type(a[0])}")
print(f"Output embedding shape: {a[0].shape}")
a[0].T

Output type: <class 'list'>
Output size: 1
Output embedding type: <class 'numpy.ndarray'>
Output embedding shape: (44, 1)


array([[18446744072083554475, 18446744073255727043,            543259558,
        18446744072252264504,           1103121568,           1399176523,
                   543259558,            797000761,           1617915982,
        18446744072931898881,           1195312295,             87281376,
                   543259558, 18446744071926469705,            723188833,
        18446744072928539352,            543259558,            797000761,
        18446744073045935379,            807352699,           1025333401,
        18446744073667574632,            785491873, 18446744073006937574,
                   823349694, 18446744072810868504,           1245366323,
                   278659925, 18446744072541521126, 18446744073147948567,
        18446744072252264504, 18446744071590211959,           1009084850,
                   823349694,           1774907633,            543259558,
                  1789020513, 18446744073434962215,            543259558,
        18446744072843995569,         